name: Deploy

on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    defaults:
      run:
        working-directory: src/dotnet
    steps:
      - uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Build template package
        run: dotnet build --configuration Release

      - name: Pack
        run: dotnet pack --configuration Release --no-build

      - name: Push to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          for file in $(find . -name "*.nupkg"); do
            dotnet nuget push "$file" -k "$NUGET_API_KEY" -s https://api.nuget.org/v3/index.json --skip-duplicate;
          done

      - name: Push to GitHub Packages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for file in $(find . -name "*.nupkg"); do
            dotnet nuget push "$file" -k "$GH_TOKEN" -s https://nuget.pkg.github.com/jfwangncs/index.json --skip-duplicate;
          done
